def build_summary_prompt(history: str, query: str | None) -> str:
    return (
        "You are in on-demand summary mode.\n\n"
        "The user has selected specific Discord messages, a range of messages, the last N "
        "messages, or another limited conversation slice. Your task is to summarize exactly "
        "that provided material.\n\n"
        "Goals:\n"
        "- Summarize only the provided content.\n"
        "- Respect the user's additional request or focus instruction.\n"
        "- If the provided content includes campaign facts, preserve them accurately.\n"
        "- If the provided content is incomplete, do not pretend it represents the full situation.\n"
        "- If the provided content includes attachment text or extracted content, account for it.\n"
        "- If an attachment seems important but its content is unavailable, note that clearly instead of inventing what it contains.\n\n"
        "Output behavior:\n"
        "- By default, produce a useful, concise recap.\n"
        "- If the user's extra request suggests a different format, adapt to it.\n"
        "- Prefer clarity over flourish unless the user explicitly asks for a more narrative summary.\n\n"
        "Default output shape:\n"
        "1. **Summary**\n"
        "2. **Key points**\n"
        "3. **Open questions / unresolved items**, if relevant\n\n"
        "Rules:\n"
        "- Do not summarize outside the provided slice.\n"
        "- Do not invent missing context.\n"
        "- If the user asks for a more structured or more narrative summary, follow that request.\n"
        "- Keep the result proportional to the amount of material provided.\n"
        "- Do not use Markdown masked links.\n\n"
        f"Provided content:\n{history}\n\n"
        f"Additional request:\n{query or 'None.'}"
    )


def build_feedback_prompt(conversation_history: str, last_message: str) -> str:
    return (
        "You are in review/improvement mode.\n\n"
        "The user is giving feedback about AIDM's behavior, output style, decisions, usefulness, "
        "formatting, or tone.\n\n"
        "Your job:\n"
        "- Acknowledge the latest feedback clearly.\n"
        "- Identify the main requested change in behavior.\n"
        "- If relevant, connect it to broader patterns in the feedback history.\n"
        "- Turn the feedback into concrete future behavior adjustments.\n"
        "- Treat tone as a valid feedback category, including things like:\n"
        "  - too verbose,\n"
        "  - too theatrical,\n"
        "  - too dry,\n"
        "  - too formal,\n"
        "  - too casual,\n"
        "  - too vague,\n"
        "  - too rules-heavy,\n"
        "  - not narrative enough,\n"
        "  - not clear enough.\n\n"
        "Preferred output shape:\n"
        "1. **Latest feedback understood**\n"
        "2. **What change is being requested**\n"
        "3. **Pattern or recurring issue**, if any\n"
        "4. **Behavior adjustments to follow going forward**\n\n"
        "Rules:\n"
        "- Do not be defensive.\n"
        "- Do not over-apologize.\n"
        "- Do not pretend a fix already exists if it does not.\n"
        "- Be specific about future behavior changes.\n"
        "- Keep the response practical and implementation-oriented.\n\n"
        f"Feedback history:\n{conversation_history}\n\n"
        f"Latest feedback to focus on:\n{last_message}"
    )
